query getCurrentUser {
  getCurrentUser {
    username
    email
    permissions
  }
}

mutation signinUser($username: String!, $password: String!) {
  signinUser(username: $username, password: $password) {
    token
  }
}

mutation authGoogle($accessToken: String!) {
  authGoogle(accessToken: $accessToken) {
    token
    email
  }
}
